const liningOptions = [
  { id: "cotton", name: "कॉटन (Cotton)", type: "checkbox" },
  { id: "poly_cotton", name: "पॉली कॉटन (Poly Cotton)", type: "checkbox" },
  { id: "shantoon", name: "शैनटून (Shantoon)", type: "checkbox" },
  {
    id: "cotton_shantoon",
    name: "कॉटन शैनटून (प्रति मीटर ₹110 अतिरिक्त) (Cotton shantoon)",
    type: "checkbox",
  },
  {
    id: "provided_by_customer",
    name: "ग्राहक द्वारा प्रदान / Provided by Customers",
    type: "checkbox",
  },
];

const doriOptions = [
  {
    id: "fabric",
    name: "कपड़ा / Kapda",
    type: "checkbox",
  },
  {
    id: "shimmer",
    name: "Shimmer",
    type: "checkbox",
  },
];

const zipperOptions = [
  { id: "front", name: "फ्रंट / Front", type: "checkbox" },
  { id: "back", name: "बैक / Back", type: "checkbox" },
  { id: "right_side", name: "राइट साइड / Right Side", type: "checkbox" },
  { id: "left_side", name: "लेफ्ट साइड / Left Side", type: "checkbox" },
];

const latkanOptions = [
  { id: "fabric", name: "फैब्रिक / Fabric", type: "checkbox" },
  {
    id: "ready_made",
    name: "रेडीमेड (जैसा कीमत लागू हो) / Ready Made (prices as applicable)",
    type: "checkbox",
  },
  {
    id: "provided_by_customer",
    name: "ग्राहक द्वारा प्रदान / Provided by Customers",
    type: "checkbox",
  },
];

const buttonOptions = [
  { id: "fabric", name: "फैब्रिक / Fabric", type: "text" },
  {
    id: "ready_made",
    name: "रेडीमेड (फैंसी) / Ready Made (Fancy)",
    type: "text",
  },
];

const paddingOptions = [
  {
    id: "light_padding",
    name: "हल्का पैडिंग / Light Padding",
    type: "checkbox",
  },
  {
    id: "heavy_padding",
    name: "भारी पैडिंग / Heavy Padding",
    type: "checkbox",
  },
];

const lacesOptions = [
  { id: "1_3_mtr", name: "1-3 मीटर / 1-3 Meters", type: "checkbox" },
  { id: "4_6_mtr", name: "4-6 मीटर / 4-6 Meters", type: "checkbox" },
  { id: "6_9_mtr", name: "6-9 मीटर / 6-9 Meters", type: "checkbox" },
  {
    id: "company",
    name: "कंपनी द्वारा (जैसा कीमत लागू हो) / Company (prices as applicable)",
    type: "checkbox",
  },
  {
    id: "customer_provided",
    name: "कस्टमर देंगे / Provided by Customers",
    type: "checkbox",
  },
];

const pipingOptions = [
  { id: "front_neck", name: " फ्रंट नेक ( Front Neck)", type: "checkbox" },
  { id: "back_neck", name: "बैक नेक (Back Neck)", type: "checkbox" },
  { id: "sleeves", name: "स्लीव (Sleeves)", type: "checkbox" },
  { id: "gher", name: " घेर (Gher)", type: "checkbox" },
  { id: "chaak", name: "चाक (Chaak)", type: "checkbox" },
];

export const tailoringDetails = {
  kurti: {
    name: "Kurti (कुर्ती)",
    details: [
      { id: "lining", name: "Astar (अस्तर)", options: liningOptions },
      { id: "dori", name: "Dori / Naada (डोरी / नाड़ा)", options: doriOptions },
      {
        id: "piping",
        name: "Piping / Kinari (पाइपिंग / किनारी)",
        options: pipingOptions,
      },
      { id: "zip", name: "Zip / Hook (ज़िप)", options: zipperOptions },
      { id: "pockets", name: "Jeb (जेब)" },
      { id: "neck_design_front", name: "Gala Aage (गला आगे)" },
      { id: "neck_design_back", name: "Gala Peeche (गला पीछे)" },
      { id: "laces", name: "Lace / Gota (लेस / गोटा)", options: lacesOptions },
      { id: "buttons", name: "Button (बटन)", options: buttonOptions },
      { id: "padded", name: "Padding (पैडिंग)", options: paddingOptions },
    ],
  },
  blouse: {
    name: "Blouse (ब्लाउज़)",
    details: [
      { id: "lining", name: "Astar (अस्तर)", options: liningOptions },
      { id: "dori", name: "Dori / Naada (डोरी / नाड़ा)", options: doriOptions },
      {
        id: "piping",
        name: "Piping / Kinari (पाइपिंग / किनारी)",
        options: pipingOptions,
      },
      { id: "zip", name: "Zip / Hook (ज़िप)", options: zipperOptions },
      {
        id: "latkan",
        name: "Latkan / Jhumka (लटकन / झुमका)",
        options: latkanOptions,
      },
      { id: "neck_design_back", name: "Gala Peeche (गला पीछे)" },
      { id: "neck_design_front", name: "Gala Aage (गला आगे)" },
      { id: "laces", name: "Lace / Gota (लेस / गोटा)", options: lacesOptions },
      { id: "buttons", name: "Button (बटन)", options: buttonOptions },
      { id: "padded", name: "Padding (पैडिंग)", options: paddingOptions },
    ],
  },
  womensuit: {
    name: "Women Suit (महिला सूट)",
    details: [
      { id: "lining", name: "Astar (अस्तर)", options: liningOptions },
      { id: "neck_design_front", name: "Gala Aage (गला आगे)" },
      { id: "neck_design_back", name: "Gala Peeche (गला पीछे)" },
      { id: "pockets", name: "Jeb (जेब)" },
      { id: "zip", name: "Zip / Hook (ज़िप)", options: zipperOptions },
      { id: "dori", name: "Dori / Naada (डोरी / नाड़ा)", options: doriOptions },
      {
        id: "piping",
        name: "Piping / Kinari (पाइपिंग / किनारी)",
        options: pipingOptions,
      },
      {
        id: "latkan",
        name: "Latkan / Jhumka (लटकन / झुमका)",
        options: latkanOptions,
      },
      { id: "laces", name: "Lace / Gota (लेस / गोटा)", options: lacesOptions },
      { id: "buttons", name: "Button (बटन)", options: buttonOptions },
      { id: "padded", name: "Padding (पैडिंग)", options: paddingOptions },
    ],
  },
  womenpants_palazzo_churidar_salwar: {
    name: "Women Pants / Palazzo / Churidar / Salwar (महिला पैंट / पलाज़ो / चूड़ीदार / सलवार)",
    details: [
      { id: "elastic_half", name: "Aadha Elastic (आधा इलास्टिक)" },
      { id: "elastic_full", name: "Pura Elastic (पूरा इलास्टिक)" },
      { id: "no_elastic", name: "Bina Elastic (बिना इलास्टिक)" },
      { id: "zip", name: "Zip / Hook (ज़िप)", options: zipperOptions },
      { id: "pockets", name: "Jeb (जेब)" },
      { id: "ankle_designs", name: "Payinche ki Design (पायंचे की डिजाइन)" },
      { id: "laces", name: "Lace / Gota (लेस / गोटा)", options: lacesOptions },
      { id: "buttons", name: "Button (बटन)", options: buttonOptions },
    ],
  },
  shararaset: {
    name: "Sharara Set (शरारा सेट)",
    details: [
      { id: "lining", name: "Astar (अस्तर)", options: liningOptions },
      { id: "neck_design_front", name: "Gala Aage (गला आगे)" },
      { id: "neck_design_back", name: "Gala Peeche (गला पीछे)" },
      { id: "pockets", name: "Jeb (जेब)" },
      { id: "zip", name: "Zip / Hook (ज़िप)", options: zipperOptions },
      { id: "dori", name: "Dori / Naada (डोरी / नाड़ा)", options: doriOptions },
      {
        id: "piping",
        name: "Piping / Kinari (पाइपिंग / किनारी)",
        options: pipingOptions,
      },
      {
        id: "latkan",
        name: "Latkan / Jhumka (लटकन / झुमका)",
        options: latkanOptions,
      },
      { id: "laces", name: "Lace / Gota (लेस / गोटा)", options: lacesOptions },
      { id: "buttons", name: "Button (बटन)", options: buttonOptions },
      { id: "padded", name: "Padding (पैडिंग)", options: paddingOptions },
    ],
  },
  coordset: {
    name: "Co-ord Set (को-ऑर्ड सेट)",
    details: [
      { id: "lining", name: "Astar (अस्तर)", options: liningOptions },
      { id: "neck_design_front", name: "Gala Aage (गला आगे)" },
      { id: "neck_design_back", name: "Gala Peeche (गला पीछे)" },
      { id: "pockets", name: "Jeb (जेब)" },
      { id: "zip", name: "Zip / Hook (ज़िप)", options: zipperOptions },
      {
        id: "piping",
        name: "Piping / Kinari (पाइपिंग / किनारी)",
        options: pipingOptions,
      },
      { id: "laces", name: "Lace / Gota (लेस / गोटा)", options: lacesOptions },
      { id: "buttons", name: "Button (बटन)", options: buttonOptions },
      { id: "padded", name: "Padding (पैडिंग)", options: paddingOptions },
    ],
  },
  dresses: {
    name: "Dresses (ड्रेसेज़)",
    details: [
      { id: "lining", name: "Astar (अस्तर)", options: liningOptions },
      { id: "neck_design_front", name: "Gala Aage (गला आगे)" },
      { id: "neck_design_back", name: "Gala Peeche (गला पीछे)" },
      { id: "pockets", name: "Jeb (जेब)" },
      { id: "zip", name: "Zip / Hook (ज़िप)", options: zipperOptions },
      {
        id: "piping",
        name: "Piping / Kinari (पाइपिंग / किनारी)",
        options: pipingOptions,
      },
      { id: "laces", name: "Lace / Gota (लेस / गोटा)", options: lacesOptions },
      { id: "buttons", name: "Button (बटन)", options: buttonOptions },
      { id: "padded", name: "Padding (पैडिंग)", options: paddingOptions },
    ],
  },
  saree: {
    name: "Saree (साड़ी)",
    details: [
      {
        id: "fold_method",
        name: "Fold Karne ka Tareeka (फोल्ड करने का तरीका)",
      },
      { id: "belt_cutting_method", name: "Belt Cutting (बेल्ट काटने की विधि)" },
      { id: "hooks", name: "Hook (हुक)" },
      { id: "laces", name: "Lace / Gota (लेस / गोटा)", options: lacesOptions },
      { id: "fall", name: "Fall (फॉल / साड़ी का किनारा)" },
      { id: "pico", name: "Pico / Picoai (पिको / पिकोाई)" },
    ],
  },
  lehenga: {
    name: "Lehenga (लहंगा)",
    details: [
      { id: "lining", name: "LINING (अस्तर)", options: liningOptions },
      { id: "zip", name: "ZIP (चेन/ज़िप)", options: zipperOptions },
      { id: "pockets", name: "POCKETS (जेब)" },
      { id: "elastic_half", name: "ELASTIC HALF (आधा इलास्टिक)" },
      { id: "elastic_full", name: "ELASTIC FULL (पूरा इलास्टिक)" },
      { id: "no_elastic", name: "NO ELASTIC (बिना इलास्टिक)" },
      { id: "laces", name: "LACES (लेस/गोटा)", options: lacesOptions },
      { id: "latkans", name: "LATKANS (लटकन/झुमका)", options: latkanOptions },
    ],
  },
  underskirt_petticoat: {
    name: "Under Skirt / Petticoat (पेटीकोट / अंडरस्कर्ट)",
    details: [
      { id: "lining", name: "LINING (अस्तर)", options: liningOptions },
      { id: "zip", name: "ZIP (चेन/ज़िप)", options: zipperOptions },
    ],
  },
  gown: {
    name: "Gown (गाउन)",
    details: [
      { id: "lining", name: "LINING (अस्तर)", options: liningOptions },
      {
        id: "neck_design_front",
        name: "NECK DESIGN FRONT (आगे का गला डिजाइन)",
      },
      { id: "neck_design_back", name: "NECK DESIGN BACK (पीछे का गला डिजाइन)" },
      { id: "pockets", name: "POCKETS (जेब)" },
      { id: "zip", name: "ZIP (चेन/ज़िप)", options: zipperOptions },
      { id: "piping", name: "PIPING (पाइपिंग)", options: pipingOptions },
      { id: "laces", name: "LACES (लेस/गोटा)", options: lacesOptions },
      { id: "buttons", name: "BUTTONS (बटन)", options: buttonOptions },
      { id: "padded", name: "PADDED (पैडिंग)", options: paddingOptions },
    ],
  },
  top: {
    name: "Top (टॉप)",
    details: [
      { id: "lining", name: "LINING (अस्तर)", options: liningOptions },
      {
        id: "neck_design_front",
        name: "NECK DESIGN FRONT (आगे का गला डिजाइन)",
      },
      { id: "neck_design_back", name: "NECK DESIGN BACK (पीछे का गला डिजाइन)" },
      { id: "zip", name: "ZIP (चेन/ज़िप)", options: zipperOptions },
      { id: "piping", name: "PIPING (पाइपिंग)", options: pipingOptions },
      { id: "laces", name: "LACES (लेस/गोटा)", options: lacesOptions },
      { id: "buttons", name: "BUTTONS (बटन)", options: buttonOptions },
      { id: "padded", name: "PADDED (पैडिंग)", options: paddingOptions },
    ],
  },
  slip: {
    name: "Slip (स्लिप)",
    details: [
      { id: "lining", name: "LINING (अस्तर)", options: liningOptions },
      {
        id: "neck_design_front",
        name: "NECK DESIGN FRONT (आगे का गला डिजाइन)",
      },
      { id: "neck_design_back", name: "NECK DESIGN BACK (पीछे का गला डिजाइन)" },
    ],
  },
  blazer: {
    name: "Blazer (ब्लेज़र)",
    details: [
      { id: "lining", name: "LINING (अस्तर)", options: liningOptions },
      { id: "padding", name: "PADDING (गद्दी/भराई)" },
      {
        id: "neck_design_front",
        name: "NECK DESIGN FRONT (आगे का गला डिजाइन)",
      },
      { id: "neck_design_back", name: "NECK DESIGN BACK (पीछे का गला डिजाइन)" },
      { id: "buttons", name: "BUTTONS (बटन)", options: buttonOptions },
    ],
  },
  pant: {
    name: "Pant (पैंट)",
    details: [
      { id: "elastic_half", name: "ELASTIC HALF (आधा इलास्टिक)" },
      { id: "elastic_full", name: "ELASTIC FULL (पूरा इलास्टिक)" },
      { id: "no_elastic", name: "NO ELASTIC (बिना इलास्टिक)" },
      { id: "zip", name: "ZIP (चेन/ज़िप)", options: zipperOptions },
      { id: "pockets", name: "POCKETS (जेब)" },
      { id: "ankle_designs", name: "ANKLE DESIGNS (पायंचे की डिजाइन)" },
      { id: "laces", name: "LACES (लेस/गोटा)", options: lacesOptions },
      { id: "buttons", name: "BUTTONS (बटन)", options: buttonOptions },
    ],
  },
  cape: {
    name: "Cape (केप)",
    details: [
      { id: "lining", name: "LINING (अस्तर)", options: liningOptions },
      { id: "pockets", name: "POCKETS (जेब)" },
      {
        id: "neck_design_front",
        name: "NECK DESIGN FRONT (आगे का गला डिजाइन)",
      },
      { id: "neck_design_back", name: "NECK DESIGN BACK (पीछे का गला डिजाइन)" },
      { id: "buttons", name: "BUTTONS (बटन)", options: buttonOptions },
      { id: "laces", name: "LACES (लेस/गोटा)", options: lacesOptions },
    ],
  },
  shrug: {
    name: "Shrug (श्रग)",
    details: [
      { id: "lining", name: "LINING (अस्तर)", options: liningOptions },
      { id: "pockets", name: "POCKETS (जेब)" },
      {
        id: "neck_design_front",
        name: "NECK DESIGN FRONT (आगे का गला डिजाइन)",
      },
      { id: "neck_design_back", name: "NECK DESIGN BACK (पीछे का गला डिजाइन)" },
      { id: "buttons", name: "BUTTONS (बटन)", options: buttonOptions },
      { id: "laces", name: "LACES (लेस/गोटा)", options: lacesOptions },
    ],
  },
  skirt: {
    name: "Skirt (स्कर्ट)",
    details: [
      { id: "lining", name: "LINING (अस्तर)", options: liningOptions },
      { id: "pockets", name: "POCKETS (जेब)" },
      { id: "buttons", name: "BUTTONS (बटन)", options: buttonOptions },
      { id: "dori", name: "DORI (डोरी/नाड़ा)", options: doriOptions },
      { id: "laces", name: "LACES (लेस/गोटा)", options: lacesOptions },
      { id: "latkans", name: "LATKANS (लटकन/झुमका)", options: latkanOptions },
    ],
  },
  ethnic_jackets: {
    name: "Ethnic Jackets (एथनिक जैकेट)",
    details: [
      { id: "lining", name: "LINING (अस्तर)", options: liningOptions },
      { id: "padding", name: "PADDING (गद्दी/भराई)" },
      {
        id: "neck_design_front",
        name: "NECK DESIGN FRONT (आगे का गला डिजाइन)",
      },
      { id: "neck_design_back", name: "NECK DESIGN BACK (पीछे का गला डिजाइन)" },
      { id: "buttons", name: "BUTTONS (बटन)", options: buttonOptions },
      { id: "laces", name: "LACES (लेस/गोटा)", options: lacesOptions },
    ],
  },
  jumpsuit: {
    name: "JumpSuit (जम्पसूट)",
    details: [
      { id: "lining", name: "LINING (अस्तर)", options: liningOptions },
      {
        id: "neck_design_front",
        name: "NECK DESIGN FRONT (आगे का गला डिजाइन)",
      },
      { id: "neck_design_back", name: "NECK DESIGN BACK (पीछे का गला डिजाइन)" },
      { id: "pockets", name: "POCKETS (जेब)" },
      { id: "zip", name: "ZIP (चेन/ज़िप)", options: zipperOptions },
      { id: "piping", name: "PIPING (पाइपिंग)", options: pipingOptions },
      { id: "laces", name: "LACES (लेस/गोटा)", options: lacesOptions },
      { id: "buttons", name: "BUTTONS (बटन)", options: buttonOptions },
      { id: "padded", name: "PADDED (पैडिंग)", options: paddingOptions },
    ],
  },
};

export const tailoringDetailsMap = {
  kurti: "Kurti (कुर्ती)",
  blouse: "Blouse (ब्लाउज़)",
  womensuit: "Women Suit (महिला सूट)",
  womenpants_palazzo_churidar_salwar:
    "Women Pants / Palazzo / Churidar / Salwar (महिला पैंट / पलाज़ो / चूड़ीदार / सलवार)",
  shararaset: "Sharara Set (शरारा सेट)",
  coordset: "Co-ord Set (को-ऑर्ड सेट)",
  dresses: "Dresses (ड्रेसेज़)",
  saree: "Saree (साड़ी)",
  lehenga: "Lehenga (लहंगा)",
  underskirt_petticoat: "Under Skirt / Petticoat (पेटीकोट / अंडरस्कर्ट)",
  gown: "Gown (गाउन)",
  top: "Top (टॉप)",
  slip: "Slip (स्लिप)",
  blazer: "Blazer (ब्लेज़र)",
  pant: "Pant (पैंट)",
  cape: "Cape (केप)",
  shrug: "Shrug (श्रग)",
  skirt: "Skirt (स्कर्ट)",
  ethnic_jackets: "Ethnic Jackets (एथनिक जैकेट)",
  jumpsuit: "JumpSuit (जम्पसूट)",
  lining: "Astar (अस्तर)",
  dori: "Dori / Naada (डोरी / नाड़ा)",
  piping: "Piping / Kinari (पाइपिंग / किनारी)",
  zip: "Zip / Hook (ज़िप)",
  pockets: "Jeb (जेब)",
  neck_design_front: "Gala Aage (गला आगे)",
  neck_design_back: "Gala Peeche (गला पीछे)",
  laces: "Lace / Gota (लेस / गोटा)",
  buttons: "Button (बटन)",
  padded: "Padding (पैडिंग)",
  latkan: "Latkan / Jhumka (लटकन / झुमका)",
  elastic_half: "Aadha Elastic (आधा इलास्टिक)",
  elastic_full: "Pura Elastic (पूरा इलास्टिक)",
  no_elastic: "Bina Elastic (बिना इलास्टिक)",
  ankle_designs: "Payinche ki Design (पायंचे की डिजाइन)",
  fold_method: "Fold Karne ka Tareeka (फोल्ड करने का तरीका)",
  belt_cutting_method: "Belt Cutting (बेल्ट काटने की विधि)",
  hooks: "Hook (हुक)",
  fall: "Fall (फॉल / साड़ी का किनारा)",
  pico: "Pico / Picoai (पिको / पिकोाई)",
  padding: "Padding (गद्दी/भराई)",
  latkans: "Latkans (लटकन/झुमका)",
  long_length: "Long Length (लॉन्ग लेंथ / पूरी लंबाई)",
  shoulder_width: "Shoulder Width (कंधे की चौड़ाई)",
  bust: "Bust (छाती का माप)",
  above_bust: "Above Bust (छाती के ऊपर का माप)",
  below_bust: "Below Bust (छाती के नीचे का माप)",
  cross_front: "Cross Front (क्रॉस फ्रंट / आगे से चौड़ाई)",
  cross_back: "Cross Back (क्रॉस बैक / पीछे से चौड़ाई)",
  dart_point: "Dart Point (डार्ट पॉइंट / निप पॉइंट)",
  waist: "Waist (कमर का माप)",
  hip_circumference: "Hip Circumference (हिप का घेरा / नितंब माप)",
  arm_hole: "Arm Hole (आर्म होल / बगल का माप)",
  bicep: "Bicep (बाइसेप / बाजू का ऊपरी माप)",
  elbow_round: "Elbow Round (कोहनी का घेरा)",
  sleeve_length: "Sleeve Length (आस्तीन की लंबाई)",
  wrist_circumference: "Wrist Circumference (कलाई का माप)",
  front_neck_depth: "Front Neck Depth (फ्रंट नेक की गहराई)",
  back_neck_depth: "Back Neck Depth (बैक नेक की गहराई)",
  around_thigh: "Around Thigh (जांघ का घेरा)",
  thigh_circumference: "Thigh Circumference (जांघ का माप)",
  medium_length_top: "Medium Length (Top) (मीडियम लंबाई - टॉप)",
  below_length_pant: "Below Length (Pant) (पैंट की लंबाई नीचे तक)",
  calf_circumference: "Calf Circumference (पिंडली का घेरा)",
  short_length: "Short Length (शॉर्ट लंबाई / छोटी लंबाई)",
  in_seam: "In Seam (इनसीम / अंदर की लंबाई)",
  nikker_length: "Nikker Length (निकर की लंबाई)",
  bottom_gher: "Bottom Gher (घेरा / बॉटम का फैलाव)",
  long_length_repeat: "Long Length (लॉन्ग लेंथ / पूरी लंबाई)",
  lower_waist_bottom: "Lower Waist Bottom (लोअर वेस्ट / कमर के नीचे का हिस्सा)",
  around_calf: "Around Calf (पिंडली का घेरा)",
  apex_to_apex: "Apex to Apex (निपल से निपल की दूरी)",
  fly_zipper_length: "Fly (Zipper Length) (फ्लाई / ज़िप की लंबाई)",
  ankle_circumference: "Ankle Circumference (टखने का घेरा)",
  knee_circumference: "Knee Circumference (घुटने का घेरा)",
  crotch_aasan: "Crotch (Aasan) (आसन / जांघों के बीच का माप)",
  around_shoulder: "Around Shoulder (कंधे का घेरा)",
  around_neck: "Around Neck (गले का माप)",
  shoulder_to_apex: "Shoulder to Apex (कंधे से निप पॉइंट तक की दूरी)",
  kas: "Kas (कस / फिटिंग माप)",
  hips: "Hips (हिप्स / नितंब का माप)",
  cotton: "कॉटन (Cotton)",
  poly_cotton: "पॉली कॉटन (Poly Cotton)",
  shantoon: "शैनटून (Shantoon)",
  cotton_shantoon: "कॉटन शैनटून (प्रति मीटर ₹110 अतिरिक्त) (Cotton shantoon)",

  front: "फ्रंट / Front",
  back: "बैक / Back",
  right_side: "राइट साइड / Right Side",
  left_side: "लेफ्ट साइड / Left Side",

  fabric: "फैब्रिक / Fabric",
  ready_made: "रेडीमेड (जैसा कीमत लागू हो) / Ready Made (prices as applicable)",
  provided_by_customer: "ग्राहक द्वारा प्रदान / Provided by Customers",

  ready_made_fancy: "रेडीमेड (फैंसी) / Ready Made (Fancy)",

  light_padding: "हल्का पैडिंग / Light Padding",
  heavy_padding: "भारी पैडिंग / Heavy Padding",

  _1_3_mtr: "1-3 मीटर / 1-3 Meters",
  _4_6_mtr: "4-6 मीटर / 4-6 Meters",
  _6_9_mtr: "6-9 मीटर / 6-9 Meters",
  company: "कंपनी द्वारा (जैसा कीमत लागू हो) / Company (prices as applicable)",
  customer_provided: "कस्टमर देंगे / Provided by Customers",

  front_neck: "फ्रंट नेक (Front Neck)",
  back_neck: "बैक नेक (Back Neck)",
  sleeves: "स्लीव (Sleeves)",
  gher: "घेर (Gher)",
  chaak: "चाक (Chaak)",
  piping_type: "Piping / Kinari (पाइपिंग / किनारी)",
  additional: "अतिरिक्त जानकारी",

  shoulder: "Shoulder / कंधा",
  "above-bust": "Above Bust / ऊपरी छाती",
  "below-bust": "Below Bust / नीचे की छाती",
  "arm-hole": "Arm hole / आर्म होल (मुड्ढा)",
  "sleeve-length": "Sleeve Length / आस्तीन की लंबाई",
  biceps: "Biceps / बाइसेप्स",
  elbow: "Elbow / कोहनी",
  "wrist-circumference": "Wrist circumference / कलाई की परिधि",
  "front-neck": "Front Neck / सामने का गला",
  "back-gala": "Back Gala / पीछे का गला",
  "short-length": "Short Length / छोटी लंबाई",
  hip: "Hip / हिप (कूल्हा)",
  "long-length": "Long Length / पूरी लंबाई",
  "slit-length": "Slit Length / चाक की लंबाई",
  "waist-pants": "Waist (Pants) / पैंट की कमर",
  "length-pants": "Length (pants) / पैंट की लंबाई",
  thigh: "Thigh / थाई",
  knee: "Knee / घुटना",
  "ankle-circumference": "Ankle circumference / मोरी",
  "dart-point": "Dart Point / डार्ट पॉइंट",
  "shoulder-strap": "Shoulder Strap / कंघी",
  "pant-hip": "Pant Hip / पैंट हिप",
};

export const bodyMeasurements = [
  { id: "long_length", name: "Long Length (लॉन्ग लेंथ / पूरी लंबाई)" },
  { id: "shoulder_width", name: "Shoulder Width (कंधे की चौड़ाई)" },
  { id: "bust", name: "Bust (छाती का माप)" },
  { id: "above_bust", name: "Above Bust (छाती के ऊपर का माप)" },
  { id: "below_bust", name: "Below Bust (छाती के नीचे का माप)" },
  { id: "cross_front", name: "Cross Front (क्रॉस फ्रंट / आगे से चौड़ाई)" },
  { id: "cross_back", name: "Cross Back (क्रॉस बैक / पीछे से चौड़ाई)" },
  { id: "dart_point", name: "Dart Point (डार्ट पॉइंट / निप पॉइंट)" },
  { id: "waist", name: "Waist (कमर का माप)" },
  {
    id: "hip_circumference",
    name: "Hip Circumference (हिप का घेरा / नितंब माप)",
  },
  { id: "arm_hole", name: "Arm Hole (आर्म होल / बगल का माप)" },
  { id: "bicep", name: "Bicep (बाइसेप / बाजू का ऊपरी माप)" },
  { id: "elbow_round", name: "Elbow Round (कोहनी का घेरा)" },
  { id: "sleeve_length", name: "Sleeve Length (आस्तीन की लंबाई)" },
  { id: "wrist_circumference", name: "Wrist Circumference (कलाई का माप)" },
  { id: "front_neck_depth", name: "Front Neck Depth (फ्रंट नेक की गहराई)" },
  { id: "back_neck_depth", name: "Back Neck Depth (बैक नेक की गहराई)" },
  { id: "around_thigh", name: "Around Thigh (जांघ का घेरा)" },
  { id: "thigh_circumference", name: "Thigh Circumference (जांघ का माप)" },
  { id: "medium_length_top", name: "Medium Length (Top) (मीडियम लंबाई - टॉप)" },
  {
    id: "below_length_pant",
    name: "Below Length (Pant) (पैंट की लंबाई नीचे तक)",
  },
  { id: "calf_circumference", name: "Calf Circumference (पिंडली का घेरा)" },
  { id: "short_length", name: "Short Length (शॉर्ट लंबाई / छोटी लंबाई)" },
  { id: "in_seam", name: "In Seam (इनसीम / अंदर की लंबाई)" },
  { id: "nikker_length", name: "Nikker Length (निकर की लंबाई)" },
  { id: "bottom_gher", name: "Bottom Gher (घेरा / बॉटम का फैलाव)" },
  { id: "long_length_repeat", name: "Long Length (लॉन्ग लेंथ / पूरी लंबाई)" },
  {
    id: "lower_waist_bottom",
    name: "Lower Waist Bottom (लोअर वेस्ट / कमर के नीचे का हिस्सा)",
  },
  { id: "around_calf", name: "Around Calf (पिंडली का घेरा)" },
  { id: "apex_to_apex", name: "Apex to Apex (निपल से निपल की दूरी)" },
  {
    id: "fly_zipper_length",
    name: "Fly (Zipper Length) (फ्लाई / ज़िप की लंबाई)",
  },
  { id: "ankle_circumference", name: "Ankle Circumference (टखने का घेरा)" },
  { id: "knee_circumference", name: "Knee Circumference (घुटने का घेरा)" },
  { id: "crotch_aasan", name: "Crotch (Aasan) (आसन / जांघों के बीच का माप)" },
  { id: "around_shoulder", name: "Around Shoulder (कंधे का घेरा)" },
  { id: "around_neck", name: "Around Neck (गले का माप)" },
  {
    id: "shoulder_to_apex",
    name: "Shoulder to Apex (कंधे से निप पॉइंट तक की दूरी)",
  },
  { id: "kas", name: "Kas (कस / फिटिंग माप)" },
  { id: "hips", name: "Hips (हिप्स / नितंब का माप)" },
];


export const bodyMeasurementDisplayOrder = {
  "Ready to wear saree": [
    "category",
    "hip",
    "waist-pants",
    "length-pants",
    "fall"
  ],

  "Kurti": [
    "category",
    "shoulder",
    "above-bust",
    "bust",
    "waist",
    "hip",
    "arm-hole",
    "sleeve-length",
    "biceps",
    "elbow",
    "wrist-circumference",
    "front-neck",
    "back-gala",
    "long-length",
    "slit-length"
  ],

  "Suit": [
    "category",
    "long-length",
    "above-bust",
    "bust",
    "waist",
    "hip",
    "shoulder",
    "arm-hole",
    "sleeve-length",
    "biceps",
    "elbow",
    "wrist-circumference",
    "front-neck",
    "back-gala",
    "dart-point",
    "length-pants",
    "waist-pants",
    "pant-hip",
    "thigh",
    "ankle-circumference"
  ],

  "Blouse": [
    "category",
    "short-length",
    "above-bust",
    "bust",
    "waist",
    "shoulder",
    "arm-hole",
    "biceps",
    "sleeve-length",
    "elbow",
    "wrist-circumference",
    "dart-point",
    "front-neck",
    "back-gala"
  ]
};

export const colorCodeArray = ["green", "yellow", "orange", "red", "gray", "blue"];